@extends('admin.layout')
@section('title', 'Editing guide')
@section('content')
<div class="admin-page-heading"><div><h1>Editing your website</h1><p class="text-muted">Choose a page from the sidebar to get started. You do not need to edit code or file paths.</p></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Change text or add a card</h2><ol class="mb-0"><li>Open the public page you want to change.</li><li>Open a section and choose <strong>Edit</strong>, or choose <strong>Add item</strong> to create another card.</li><li>Change the text and click <strong>Save changes</strong>. Use <strong>View page</strong> to check the result.</li></ol><p class="small text-muted mt-3 mb-0">Formatted text has Bold, Italic and list buttons. You can leave HTML source and Design settings unchanged. Smaller position numbers place items earlier in a list.</p></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Replace an image, video or logo</h2><ol class="mb-0"><li>On the page editor, open <strong>Images, videos & logos</strong>.</li><li>Search for the item or section. Search for <strong>Website logo</strong> to find the main logo.</li><li>Choose a thumbnail from the media library, or upload a file from your computer.</li><li>Click the Save button on that card before changing another file.</li></ol><p class="small text-muted mt-3 mb-0">Shared images and logos are marked. Changing one also updates the other pages that use it. To add an image to a new card, use Add item in that section.</p></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Change menus, submenus and links</h2><ol class="mb-0"><li>Open <strong>Navigation</strong>.</li><li>Use <strong>Add menu item</strong> for a main menu link. Use <strong>Add submenu</strong> beside Services, Company or another dropdown for a child link.</li><li>Enter the label visitors should see. Choose a website page from the list, or paste a full web address.</li><li>Save the menu item. Use the arrow buttons to move it up or down.</li></ol><p class="small text-muted mt-3 mb-0">A Dropdown menu opens a list of links. A Button emphasizes a link. Show on website controls visibility without deleting the item.</p></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Change the footer</h2><p class="mb-0">Open <strong>Footer</strong> to update contact details, social media links, company links and footer text. Link fields include a website-page selector.</p></div></div>
<div class="card"><div class="card-body"><h2 class="h5">Shared content and deleted items</h2><p>Page editors include the shared sections used on that page. Shared content is marked because an edit affects every page using the same content.</p><p class="mb-0">Deleted page content stays in its section with a <strong>Restore</strong> button. Earlier layouts are kept in a collapsed group. Changes become visible on the public website when you save.</p></div></div>
@endsection
