<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    // An immutable upgrade map: retain row IDs, media paths, soft deletes and admin edits.
    private const TABLES = [
        'cms_page_ai_automation' => 'page_ai_automation_sections',
        'cms_page_clients' => 'page_clients_sections',
        'cms_page_home' => 'page_home_sections',
        'cms_site_public' => 'site_public_sections',
        'cms_clients_client_strip' => 'clients_client_strip_sections',
        'cms_clients_client_strip_clients' => 'clients_client_strip_clients',
        'cms_clients_deck' => 'clients_deck_sections',
        'cms_clients_deck_screens' => 'client_stories',
        'cms_footer' => 'footer_sections',
        'cms_home_assessment' => 'home_assessment_sections',
        'cms_home_cta_banner' => 'home_cta_banner_sections',
        'cms_home_defend' => 'home_defend_sections',
        'cms_home_hero' => 'home_hero_sections',
        'cms_home_network' => 'home_network_sections',
        'cms_home_our_story' => 'home_our_story_sections',
        'cms_home_our_story_milestones' => 'timeline_milestones',
        'cms_home_solutions' => 'home_solutions_sections',
        'cms_home_tech_diagram' => 'home_tech_diagram_sections',
        'cms_home_threats' => 'home_threats_sections',
        'cms_nav' => 'nav_sections',
        'cms_nav_primary_routes' => 'nav_primary_routes',
        'cms_soc_benefits' => 'soc_benefits_sections',
        'cms_soc_benefits_benefits' => 'soc_benefits_benefits',
        'cms_soc_calculator' => 'soc_calculator_sections',
        'cms_soc_comparison' => 'soc_comparison_sections',
        'cms_soc_comparison_rows' => 'soc_comparison_rows',
        'cms_soc_expert' => 'soc_expert_sections',
        'cms_soc_hero' => 'soc_hero_sections',
        'cms_soc_hero_height_items' => 'soc_hero_height_items',
        'cms_soc_matrix' => 'soc_matrix_sections',
        'cms_soc_matrix_caps' => 'soc_matrix_caps',
        'cms_soc_matrix_tiers' => 'soc_matrix_tiers',
        'cms_soc_numbers' => 'soc_numbers_sections',
        'cms_soc_pricing' => 'soc_pricing_sections',
        'cms_soc_pricing_plans' => 'soc_pricing_plans',
        'cms_soc_reviews' => 'soc_reviews_sections',
        'cms_soc_reviews_reviews' => 'soc_reviews_reviews',
        'cms_soc_sensor' => 'soc_sensor_sections',
        'cms_soc_sensor_sensors' => 'soc_sensor_sensors',
        'cms_vapt_benefits' => 'vapt_benefits_sections',
        'cms_vapt_benefits_benefits' => 'vapt_benefits_benefits',
        'cms_vapt_boxes' => 'vapt_boxes_sections',
        'cms_vapt_boxes_boxes' => 'vapt_boxes_boxes',
        'cms_vapt_calculator' => 'vapt_calculator_sections',
        'cms_vapt_hero' => 'vapt_hero_sections',
        'cms_vapt_hero_height_items' => 'vapt_hero_height_items',
        'cms_vapt_hero_step_items' => 'vapt_hero_step_items',
        'cms_vapt_matrix' => 'vapt_matrix_sections',
        'cms_vapt_matrix_rows' => 'vapt_matrix_rows',
        'cms_vapt_numbers' => 'vapt_numbers_sections',
        'cms_vapt_posture' => 'vapt_posture_sections',
        'cms_vapt_posture_nodes' => 'vapt_posture_nodes',
        'cms_vapt_reviews' => 'vapt_reviews_sections',
        'cms_vapt_reviews_reviews' => 'vapt_reviews_reviews',
        'cms_vapt_success' => 'vapt_success_sections',
        'cms_vciso_hero' => 'vciso_hero_sections',
        'cms_vciso_hero_left_nodes' => 'vciso_hero_left_nodes',
        'cms_vciso_hero_right_nodes' => 'vciso_hero_right_nodes',
        'cms_vciso_product' => 'vciso_product_sections',
        'cms_vciso_product_modules' => 'vciso_product_modules',
        'cms_page_service_detail' => 'page_service_detail_sections',
        'cms_page_soc' => 'page_soc_sections',
        'cms_page_vapt' => 'page_vapt_sections',
        'cms_page_vciso' => 'page_vciso_sections',
        'cms_layout_portfolio' => 'layout_portfolio_sections',
        'cms_page_about' => 'page_about_sections',
        'cms_page_capacity_building' => 'page_capacity_building_sections',
        'cms_page_capacity_building_item_items' => 'page_capacity_building_item_items',
        'cms_page_capacity_building_w_items' => 'page_capacity_building_w_items',
        'cms_page_career' => 'page_career_sections',
        'cms_page_career_w_items' => 'page_career_w_items',
        'cms_page_career_w_items_2' => 'page_career_w_items2s',
        'cms_page_career_job_items' => 'page_career_job_items',
        'cms_page_contact' => 'page_contact_sections',
        'cms_legacy_pages_defense_services' => 'legacy_pages_defense_services_sections',
        'cms_legacy_pages_defense_services_offensive' => 'legacy_pages_defense_services_offensives',
        'cms_legacy_pages_defense_services_defensive' => 'legacy_pages_defense_services_defensives',
        'cms_page_defensive_security_services' => 'page_defensive_security_services_sections',
        'cms_page_defensive_security_services_items' => 'page_defensive_security_services_items',
        'cms_legacy_pages_home' => 'legacy_pages_home_sections',
        'cms_legacy_pages_home_step_items' => 'legacy_pages_home_step_items',
        'cms_legacy_pages_home_sol_items' => 'legacy_pages_home_sol_items',
        'cms_legacy_pages_home_case_items' => 'legacy_pages_home_case_items',
        'cms_legacy_pages_home_m_items' => 'legacy_pages_home_m_items',
        'cms_page_it_audit' => 'page_it_audit_sections',
        'cms_page_it_audit_v_items' => 'page_it_audit_v_items',
        'cms_page_it_audit_step_items' => 'page_it_audit_step_items',
        'cms_page_offensive_security_services' => 'page_offensive_security_services_sections',
        'cms_page_offensive_security_services_items' => 'page_offensive_security_services_items',
        'cms_page_our_team' => 'page_our_team_sections',
        'cms_page_our_team_team' => 'team_members',
        'cms_shared_security_service_group' => 'shared_security_service_group_sections',
        'cms_page_services' => 'page_services_sections',
        'cms_legacy_pages_soc' => 'legacy_pages_soc_sections',
        'cms_legacy_pages_soc_row_items' => 'legacy_pages_soc_row_items',
        'cms_legacy_pages_soc_b_items' => 'legacy_pages_soc_b_items',
        'cms_legacy_pages_soc_s_items' => 'legacy_pages_soc_s_items',
        'cms_legacy_pages_soc_plan_items' => 'legacy_pages_soc_plan_items',
        'cms_legacy_pages_vapt' => 'legacy_pages_vapt_sections',
        'cms_legacy_pages_vapt_p_items' => 'legacy_pages_vapt_p_items',
        'cms_legacy_pages_vapt_row_items' => 'legacy_pages_vapt_row_items',
        'cms_legacy_pages_vapt_b_items' => 'legacy_pages_vapt_b_items',
        'cms_legacy_pages_vciso' => 'legacy_pages_vciso_sections',
        'cms_legacy_pages_vciso_cap_items' => 'legacy_pages_vciso_cap_items',
        'cms_legacy_pages_vciso_cap_items_2' => 'legacy_pages_vciso_cap_items2s',
        'cms_legacy_pages_vciso_c_items' => 'legacy_pages_vciso_c_items',
        'cms_shared_about_industries_clients' => 'shared_about_industries_clients_sections',
        'cms_shared_about_industries_clients_about_industries' => 'shared_about_industries_clients_about_industries',
        'cms_shared_about_industries_clients_about_clients' => 'shared_about_industries_clients_about_clients',
        'cms_shared_clients' => 'shared_clients_sections',
        'cms_shared_clients_clients' => 'clients',
        'cms_shared_navbar' => 'shared_navbar_sections',
        'cms_shared_navbar_service_links' => 'shared_navbar_service_links',
        'cms_shared_navbar_service_route_names' => 'shared_navbar_service_route_names',
        'cms_shared_page_hero' => 'shared_page_hero_sections',
        'cms_shared_reviews' => 'shared_reviews_sections',
        'cms_shared_reviews_reviews' => 'shared_reviews_reviews',
        'cms_shared_talk_to_expert' => 'shared_talk_to_expert_sections',
        'cms_legacy_portfolio_index' => 'legacy_portfolio_index_sections',
        'cms_services' => 'services',
        'cms_page_ai_automation_cards' => 'page_ai_automation_cards',
        'cms_page_ai_automation_cards_2' => 'page_ai_automation_cards2s',
        'cms_page_ai_automation_timeline' => 'page_ai_automation_timelines',
        'cms_footer_wordmark' => 'footer_wordmarks',
        'cms_footer_cards' => 'footer_cards',
        'cms_footer_col_12' => 'footer_col12s',
        'cms_home_cta_banner_cta2_line' => 'home_cta_banner_cta2_lines',
        'cms_home_defend_dao_stats' => 'home_defend_dao_stats',
        'cms_home_hero_drift' => 'home_hero_drifts',
        'cms_home_network_clnetcard' => 'home_network_clnetcards',
        'cms_home_network_net_stats' => 'home_network_net_stats',
        'cms_home_network_net_floats' => 'home_network_net_floats',
        'cms_home_our_story_story_stats' => 'home_our_story_story_stats',
        'cms_home_tech_diagram_process_stage_grid' => 'home_tech_diagram_process_stage_grids',
        'cms_home_threats_th_floats' => 'home_threats_th_floats',
        'cms_soc_expert_links' => 'soc_expert_links',
        'cms_soc_hero_soc_log' => 'soc_hero_soc_logs',
        'cms_soc_numbers_cards' => 'soc_numbers_cards',
        'cms_vapt_hero_vapt_logs' => 'vapt_hero_vapt_logs',
        'cms_vapt_numbers_vapt_number_grid' => 'vapt_numbers_vapt_number_grids',
        'cms_vapt_success_vapt_success_stats' => 'vapt_success_vapt_success_stats',
        'cms_page_capacity_building_links' => 'page_capacity_building_links',
        'cms_page_capacity_building_links_2' => 'page_capacity_building_links2s',
        'cms_page_contact_links' => 'page_contact_links',
        'cms_page_contact_cards' => 'page_contact_cards',
        'cms_legacy_pages_home_console_stats' => 'legacy_pages_home_console_stats',
        'cms_legacy_pages_home_links' => 'legacy_pages_home_links',
        'cms_page_it_audit_links' => 'page_it_audit_links',
        'cms_legacy_pages_soc_cards' => 'legacy_pages_soc_cards',
        'cms_legacy_pages_soc_tr_items' => 'legacy_pages_soc_tr_items',
        'cms_legacy_pages_vapt_links' => 'legacy_pages_vapt_links',
        'cms_legacy_portfolio_index_cards' => 'legacy_portfolio_index_cards',
        'cms_legacy_portfolio_index_links' => 'legacy_portfolio_index_links',
        'cms_legacy_portfolio_index_links_2' => 'legacy_portfolio_index_links2s',
        'cms_legacy_portfolio_index_links_3' => 'legacy_portfolio_index_links3s',
        'cms_threat_feed_events' => 'threat_feed_events',
        'cms_soc_live_events' => 'soc_live_events',
        'cms_vapt_live_events' => 'vapt_live_events',
        'cms_team_units' => 'team_units',
        'cms_navigation_company_links' => 'navigation_company_links',
        'cms_navigation_specialized_links' => 'navigation_specialized_links',
        'cms_footer_company_links' => 'footer_company_links',
        'cms_footer_specialized_links' => 'footer_specialized_links',
        'cms_training_packages' => 'training_packages',
    ];

    public function up(): void
    {
        foreach (self::TABLES as $from => $to) {
            Schema::rename($from, $to);
        }
    }

    public function down(): void
    {
        foreach (array_reverse(self::TABLES, true) as $from => $to) {
            Schema::rename($to, $from);
        }
    }
};
