<?php

/*
|--------------------------------------------------------------------------
| Cyberlog service catalogue - single source of truth (12 services)
|--------------------------------------------------------------------------
| These entries drive the navbar Services dropdown, the All Services page,
| home solution cards, and the footer Services list.
*/

return [
    [
        'title'  => 'Security Operations Center Implementation',
        'icon'   => 'fa-desktop',
        'route'  => 'soc',
        'group'  => 'primary',
        'kicker' => 'THREAT DETECTION',
        'desc'   => 'Implement centralized log collection, SIEM monitoring, alert rules, threat detection, incident triage, and response support.',
        'tags'   => ['SOC', 'SIEM', 'Incident Monitoring'],
        'detail' => null,
    ],
    [
        'title'  => 'Threat Intelligence',
        'icon'   => 'fa-satellite-dish',
        'route'  => 'threat-intelligence',
        'group'  => 'defensive',
        'kicker' => 'EARLY WARNING',
        'desc'   => 'Monitor emerging threats, leaked credentials, phishing campaigns, exposed assets, and attacker activity with actionable intelligence.',
        'tags'   => ['Threat Monitoring', 'Leaked Credentials', 'Risk Insights'],
        'detail' => null,
    ],
    [
        'title'  => 'Vulnerability Assessment & Penetration Testing',
        'icon'   => 'fa-bug',
        'route'  => 'vapt',
        'group'  => 'primary',
        'kicker' => 'REAL WORLD SECURITY TESTING',
        'desc'   => 'Identify, validate, and prioritize vulnerabilities across applications, networks, APIs, mobile platforms, cloud, and infrastructure.',
        'tags'   => ['VAPT', 'Web Testing', 'Network Testing'],
        'detail' => null,
    ],
    [
        'title'  => 'Red Team Assessment',
        'icon'   => 'fa-user-secret',
        'route'  => 'red-team',
        'group'  => 'offensive',
        'kicker' => 'ATTACK SIMULATION',
        'desc'   => 'Simulate real-world attack scenarios to test people, processes, technology, detection capability, and response readiness.',
        'tags'   => ['Attack Simulation', 'Defense Testing', 'Security Readiness'],
        'detail' => null,
    ],
    [
        'title'  => 'Web, API & Mobile Application Security Testing',
        'icon'   => 'fa-mobile-screen-button',
        'route'  => 'app-security-testing',
        'group'  => 'offensive',
        'kicker' => 'APPLICATION SECURITY',
        'desc'   => 'Test web, API, Android, and iOS applications for authentication, authorization, session, input validation, and data exposure risks.',
        'tags'   => ['OWASP Top 10', 'API Security', 'Mobile Security'],
        'detail' => null,
    ],
    [
        'title'  => 'Network Security Assessment',
        'icon'   => 'fa-network-wired',
        'route'  => 'network-security',
        'group'  => 'offensive',
        'kicker' => 'INFRASTRUCTURE SECURITY',
        'desc'   => 'Assess internal and external networks, exposed services, firewalls, servers, wireless networks, segmentation, and access controls.',
        'tags'   => ['Firewall Review', 'Network Exposure', 'Segmentation'],
        'detail' => null,
    ],
    [
        'title'  => 'Source Code Security Audit',
        'icon'   => 'fa-code',
        'route'  => 'secure-code-review',
        'group'  => 'primary',
        'kicker' => 'SECURE CODE REVIEW',
        'desc'   => 'Review source code, dependencies, and application security weaknesses using secure coding practices, SAST, and DAST approaches.',
        'tags'   => ['SAST', 'DAST', 'Secure Coding'],
        'detail' => null,
    ],
    [
        'title'  => 'Digital Forensics & Incident Response',
        'icon'   => 'fa-fingerprint',
        'route'  => 'digital-forensics',
        'group'  => 'defensive',
        'kicker' => 'INVESTIGATION SUPPORT',
        'desc'   => 'Investigate cyber incidents, analyze evidence, support containment, and provide practical recommendations for recovery and prevention.',
        'tags'   => ['Forensics', 'Incident Response', 'Evidence Analysis'],
        'detail' => null,
    ],
    [
        'title'  => 'Secure Backup & Recovery Solutions',
        'icon'   => 'fa-server',
        'route'  => 'backup-recovery',
        'group'  => 'primary',
        'kicker' => 'OPERATIONAL RESILIENCE',
        'desc'   => 'Strengthen backup strategy, recovery readiness, and data protection to help critical systems survive disruption and cyber incidents.',
        'tags'   => ['Secure Backup', 'Recovery Planning', 'Data Protection'],
        'detail' => null,
    ],
    [
        'title'  => 'IT Security Audit & ISO 27001',
        'icon'   => 'fa-clipboard-check',
        'route'  => 'it-audit',
        'group'  => 'primary',
        'kicker' => 'COMPLIANCE READINESS',
        'desc'   => 'Review IT controls, identify security gaps, assess governance, and support ISO/IEC 27001 implementation and audit readiness.',
        'tags'   => ['IT Audit', 'ISO 27001', 'Control Review'],
        'detail' => null,
    ],
    [
        'title'  => 'Cybersecurity Consultancy',
        'icon'   => 'fa-briefcase',
        'route'  => 'security-consultancy',
        'group'  => 'primary',
        'kicker' => 'SECURITY ADVISORY',
        'desc'   => 'Provide expert guidance on security strategy, policy improvement, risk-based decisions, and long-term cybersecurity roadmap development.',
        'tags'   => ['Security Roadmap', 'Risk Advisory', 'Policy Support'],
        'detail' => null,
    ],
    [
        'title'  => 'Awareness & Security Training',
        'icon'   => 'fa-graduation-cap',
        'route'  => 'capacity-building',
        'group'  => 'primary',
        'kicker' => 'HUMAN DEFENSE',
        'desc'   => 'Deliver role-based training on cyber hygiene, phishing, social engineering, secure practices, and organizational security awareness.',
        'tags'   => ['Awareness Training', 'Phishing Readiness', 'Staff Training'],
        'detail' => null,
    ],
];
