<?php

return [
    'nav' => 'Website logo & menu button',
    'site_public' => 'Browser tab title & website icon',
    'layout_portfolio' => 'Page layout defaults',
    'shared_page_hero' => 'Default page banner',
    'shared_talk_to_expert' => 'Contact banner & button',
    'shared_security_service_group' => 'Service group headings',
    'footer' => 'Footer headings & contact details',
    'footer_col_12' => 'Main service links',
    'footer_company_links' => 'Company links',
    'footer_specialized_links' => 'Specialized service links',
    'footer_cards' => 'Social media links',
    'footer_wordmark' => 'Footer brand lettering',
    'home_solutions' => 'Services section headings',
    'home_our_story_story_stats' => 'Company statistics',
    'page_it_audit_v_items' => 'Benefits of an IT audit',
    'page_it_audit_step_items' => 'Audit process steps',
    'page_it_audit_links' => 'Audit statistics',
    'page_capacity_building_item_items' => 'Training benefits',
    'page_capacity_building_w_items' => 'Training approach',
    'page_career_w_items' => 'Career highlight cards',
    'page_career_w_items_2' => 'Workplace benefit cards',
    'page_career_job_items' => 'Job openings',
    'page_contact_cards' => 'Contact information cards',
    'soc_hero_height_items' => 'Activity chart bars',
    'vapt_hero_height_items' => 'Activity chart bars',
    'vapt_hero_step_items' => 'Scanning animation steps',
    'soc_hero_soc_log' => 'Live activity display',
    'vapt_hero_vapt_logs' => 'Scanning activity display',
    'soc_matrix_caps' => 'Service coverage comparison',
    'soc_matrix_tiers' => 'Service comparison column headings',
    'vapt_numbers_vapt_number_grid' => 'Assessment statistics',
    'vciso_hero_left_nodes' => 'Product diagram labels (left)',
    'vciso_hero_right_nodes' => 'Product diagram labels (right)',
    'threat_feed_events' => 'Threat feed messages',
    'soc_live_events' => 'SOC activity messages',
    'vapt_live_events' => 'VAPT activity messages',
];
