name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/mobility/cyberlogportfolio.mobility.com.bd

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize:clear

            php artisan config:cache
